name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: cloudbizcrm
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: kwasd5af
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_NAME: cloudbizcrm
      DB_USER: postgres
      DB_PASSWORD: kwasd5af
      DB_HOST: localhost
      DB_PORT: 5432

    steps:
      - uses: actions/checkout@v3
      - name: Dump database env
        run: |
          echo "DB_HOST=$DB_HOST"
          python - <<EOF
import os
print("settings DB_HOST:", os.environ.get("DB_HOST"))
EOF
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests
        run: python manage.py test