name: Django CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: cloudbizcrm
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: kwasd5af
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_NAME: cloudbizcrm
      DB_USER: postgres
      DB_PASSWORD: kwasd5af
      DB_HOST: localhost
      DB_PORT: 5432
    steps:
      - uses: actions/checkout@v3
        env:
          DB_NAME: cloudbizcrm
          DB_USER: postgres
          DB_PASSWORD: kwasd5af
          DB_HOST: localhost
          DB_PORT: 5432
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        env:
          DB_NAME: cloudbizcrm
          DB_USER: postgres
          DB_PASSWORD: kwasd5af
          DB_HOST: localhost
          DB_PORT: 5432
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          DB_NAME: cloudbizcrm
          DB_USER: postgres
          DB_PASSWORD: kwasd5af
          DB_HOST: localhost
          DB_PORT: 5432
      - name: Run migrations
        run: python manage.py migrate
        env:
          DB_NAME: cloudbizcrm
          DB_USER: postgres
          DB_PASSWORD: kwasd5af
          DB_HOST: localhost
          DB_PORT: 5432
      - name: Run tests
        run: python manage.py test
        env:
          DB_NAME: cloudbizcrm
          DB_USER: postgres
          DB_PASSWORD: kwasd5af
          DB_HOST: localhost
          DB_PORT: 5432
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.EC2_HOST }} "cd /home/ec2-user/TechNova-Solutions && git pull && docker compose down && docker compose up -d --build"
        env:
          DB_NAME: cloudbizcrm
          DB_USER: postgres
          DB_PASSWORD: kwasd5af
          DB_HOST: localhost
          DB_PORT: 5432