name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: cloudbizcrm
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: kwasd5af
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: python manage.py migrate
        env:
          DATABASE_URL: postgres://postgres:kwasd5af@localhost:5432/cloudbizcrm
      - name: Run tests
        run: python manage.py test
        env:
          DATABASE_URL: postgres://postgres:kwasd5af@localhost:5432/cloudbizcrm
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.EC2_HOST }} "
            cd /home/ec2-user/TechNova-Solutions &&
            git config pull.rebase false &&
            git add . &&
            git commit -am 'Auto-commit local changes before deploy' || true &&
            git pull --no-rebase &&
            docker compose down &&
            docker compose up -d --build
          "
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}